//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentReporting
    {
        public int Id { get; set; }
        public int WorkItemId { get; set; }
        public string State { get; set; }
        public string Summary { get; set; }
        public System.DateTime InsertDate { get; set; }
        public bool IsComplete { get; set; }
        public System.DateTime UpdateDate { get; set; }
    }
}
